# **SDA dalam Python**

### Nama : Kafka Ramadityo
### NIM  : 2022071036
### NIM  : Desain dan Analisis Algoritma


In [55]:
from datetime import datetime
cdt = datetime.now()
date = '%s/%s/%s' % (cdt.day, cdt.month, cdt.year)

mahasiswa = ["Kafka Ramadityo", 2022071036, "Informatika", "Desain dan Analisis Algoritma", date, "Universitas Pembangunan Jaya"];
for item in mahasiswa:
  print(item)

Kafka Ramadityo
2022071036
Informatika
Desain dan Analisis Algoritma
14/9/2023
Universitas Pembangunan Jaya


## **List**

In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
result = bin_colors[1]

print(result)

Green


In [ ]:
mahasiswa[1]

2022071036

In [ ]:
mahasiswa[5]

'Universitas Pembangunan Jaya'

## **List slicing**

In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
result = bin_colors[0:2]

print(result)

['Red', 'Green']


Cetak NIM dan Prodi menggunakan slicing!

In [ ]:
mahasiswa = ["Kafka Ramadityo", 2022071036, "Informatika", "Desain dan Analisis Algoritma", date, "Universitas Pembangunan Jaya"];

slicedList = mahasiswa[1:3]

print(slicedList)

[2022071036, 'Informatika']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']

for colors in bin_colors:
  print(colors , "Square")

Red Square
Green Square
Blue Square
Yellow Square


## **Cetak isi list “Mahasiswa”, tambahkan kata “UPJ” di depan!**

In [ ]:
mahasiswa = ["Kafka Ramadityo", 2022071036, "Informatika", "Desain dan Analisis Algoritma", date, "Universitas Pembangunan Jaya"];
mahasiswa.insert(0, "UPJ")

print(mahasiswa)


['UPJ', 'Kafka Ramadityo', 2022071036, 'Informatika', 'Desain dan Analisis Algoritma', '13/9/2023', 'Universitas Pembangunan Jaya']


## **Tuples**

In [ ]:
bin_colors=('Red','Green','Blue','Yellow')
tuples_1 = bin_colors[1]
tuples_2 = bin_colors[2:]

print(tuples_1)
print(tuples_2)

Green
('Blue', 'Yellow')


## **Susun Tuple bernama “UPJ”,  isi dengan Universitas, Pembangunan, Jaya**

In [ ]:
UPJ = ('Universitas', 'Pembangunan', 'Jaya')

print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


## **Nested Tuple**

In [ ]:
hari_awal = ('senin', 'selasa', 'rabu')
hari_akhir = ('kamis', 'jumat', 'sabtu')

hari = (hari_awal, hari_akhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


Buat  tuple bersarang bernama “nested_tuple” dengan nilai :
*    Pertama = 100
*    Kedua = 200, 400, 600
*    Ketiga = 300
*    Keempat = 400, 800

In [ ]:
kedua = (200, 400, 600)
keempat = (400, 800)

nested_tuple = (100, kedua, 300, keempat)
print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


## **Dictionary**

In [ ]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red",
}

print(bin_colors)

print("")

bin_colors.get('approved_color')

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}



'Green'

In [ ]:
bin_colors['approved_color'] = 'Purple'
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


## **Latihan membuat Dictionary**

In [ ]:
mahasiswa_object = {
    'nama' : 'Kafka Ramadityo',
    'NIM' : 2022071036,
    'Prodi' : 'Informatika',
    'Universitas' : 'UPJ',
}

print(mahasiswa_object)

{'nama': 'Kafka Ramadityo', 'NIM': 2022071036, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


## **Sets**

In [ ]:
green = {'grass', 'leaves'}
print(green)

green = {'grass', 'leaves', 'leaves'}
print(green)

{'grass', 'leaves'}
{'grass', 'leaves'}


In [ ]:
set_01 = {4,5,6,2}
print(set_01)

set_02 = set()
set_03 = set([2,1,4,3])
print(type(set_02))
print(set_03)


{2, 4, 5, 6}
<class 'set'>
{1, 2, 3, 4}


In [ ]:
set_04 = {2,3,4,5,6}

set_04.add(1)
print(set_04)

{1, 2, 3, 4, 5, 6}


In [ ]:
set_05 = {1, 2, 3, 4, 5, 6, 7, 8}

set_05.discard(4)
print(set_05)

set_05.add(10)
print(set_05)

{1, 2, 3, 5, 6, 7, 8}
{1, 2, 3, 5, 6, 7, 8, 10}


## **Union set**

In [ ]:
set_A = {1,2,3,4}
set_B = {3,4,5,6}

print(set_A|set_B)
print(set_A.union(set_B))


{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


In [ ]:
print(set_A & set_B)
print(set_A.intersection(set_B))


{3, 4}
{3, 4}


In [ ]:
print(set_A - set_B)
print(set_A.difference(set_B))

print(set_B - set_A)
print(set_B.difference(set_A))

{1, 2}
{1, 2}
{5, 6}
{5, 6}


In [ ]:
print(set_A ^ set_B)
print(set_A.symmetric_difference(set_B))


{1, 2, 5, 6}
{1, 2, 5, 6}


## **Latihan membuat Union set**

In [ ]:
red = {'dandelion', 'leaves', 'fire hydrant'}
yellow = {'rose', 'blood', 'leaves', 'fire hydrant'}

print(yellow | red)
print(yellow & red)

{'leaves', 'rose', 'dandelion', 'blood', 'fire hydrant'}
{'leaves', 'fire hydrant'}


## **DataFrames**

In [ ]:
import pandas as pd
df = pd.DataFrame([
['1', 'Fares', 32, True],
['2', 'Elena', 23, False],
['3', 'Steven', 40, True]])

print(df)

   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [ ]:
df.columns = ['id', 'name', 'age', 'decision']

print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


In [ ]:
# Seleksi kolom

df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
# Seleksi baris

df.iloc[1:3,:]

id    name  age  desicion
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[df.age>30]

id    name  age  desicion
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
df[(df.age<35)&(df.decision==True)]


id   name  age  decision
0  1  Fares   32      True

## **Memberikan index label seperti pada Series**

In [ ]:
data = {'satu': [1,1,1,1,1],
        'dua' : [2,2,2,2,2],
        'tiga': [3,3,3,3,3]}

df = pd.DataFrame(data, index=['a','b','c','d','e'])

df.head()


satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

## **Buat dataframe bernama mhs**

In [20]:
import pandas as pd

data = {
    'No': [1, 2, 3],
    'Prodi': ['Informatika', 'Sistem Informarsi', 'Teknik Sipil'],
    'Mahasiswa': [50, 55, 40],
    'Laki-laki': [30, 30, 30],
    'Perempuan': [20, 25, 10]
}

df = pd.DataFrame(data)

def left_align(x):
    return 'text-align: left'

styled_df = df.style.applymap(left_align, subset=['No', 'Prodi', 'Mahasiswa', 'Laki-laki'])

header_style = [{'selector': 'th', 'props': [('text-align', 'left')]}]

styled_df.set_table_styles(header_style, axis=1)

styled_df




## **Matrix**

In [23]:
import numpy as np

myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

print(type(myMatrix))


[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


## **Transpose Matrix**

In [24]:
import numpy as np
matriksC = np.array([[1,2,3],
		     [4,5,6]])
print("Matriks C : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Tranpose Matriks C : ")
print(transpose_matriks)

Matriks C : 
[[1 2 3]
 [4 5 6]]
Tranpose Matriks C : 
[[1 4]
 [2 5]
 [3 6]]


## **Latihan**

### Buatlah Matrix dengan nilai berikut
      [ 100  200  300  ]
      [ 700  600  500  ]
      [ 900  1000 800 ]
Lakukan transpose matrix!


In [26]:
import numpy as np
matriks = np.array([
    [100,200,300],
		[700,600,500],
		[900,1000,800],
])
print("Matriks C : ")
print(matriks)

transpose_matriks = np.transpose(matriks)

print("Tranpose Matriks: ")
print(transpose_matriks)

Matriks C : 
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Tranpose Matriks: 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


## **Tipe data abstrak: Vector**

In [28]:
myVector = [22,33,44,55]
print(myVector)

print(type(myVector))


[22, 33, 44, 55]
<class 'list'>


In [32]:
mprintyVector = np.array([22,33,44,55])
print(mprintyVector)

print(type(mprintyVector))


[22 33 44 55]
<class 'numpy.ndarray'>


## **Tipe data abstrak: Stack**

In [33]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.items)

In [34]:
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [35]:
stack.pop()

'Yellow'

In [36]:
stack.isEmpty()

False

## **Tipe data abstrak: Queue**

In [43]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0, item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [44]:
queue = Queue()

In [45]:
queue.enqueue('Red')

In [47]:
queue.enqueue('Green')

In [48]:
queue.enqueue('Blue')

In [49]:
queue.enqueue('Yellow')

In [50]:
print(queue.size())

4


In [51]:
print(queue.dequeue())

Red


In [52]:
print(queue.dequeue())

Green


## **Tipe data abstrak: Queue**

In [53]:
class Node:
    def __init__(self,data):
        self.left = None
        self.right = None
        self.data = data
    def PrintTree(self):
        if self.left:
            self.left.PrintTree()
        print( self.data),
        if self.right:
            self.right.PrintTree()


In [54]:
root = Node(2)#root
root.left = Node(3) #child kiri dari root
root.right = Node(5) #child kanan dari root
root.left.left = Node(7) #child kiri dari 3
root.left.right = Node(9) #child kanan dari 3
root.right.left = Node(11) #child kiri dari 5
root.right.right = Node(13) #child kanan dari 5
root.PrintTree()


7
3
9
2
11
5
13
